config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  get 'hello_world', to: 'hello_world#index'

  namespace :api do
    namespace :v1 do
      resources :favorite_photos, only: [:update, :destroy, :index]
      resources :users, only: :index
      resources :generic_images, only: :index
    end
  end

  resource :home, controller: 'home'
  resources :favorites, only: :index
  resources :garages, only: [:new, :create]
  resource :profile, controller: 'profile', only: [:show, :edit]

  root to: 'home#show'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :followable, polymorphic: true
end

app/models/garage.rb
class Garage < ApplicationRecord
  belongs_to :user
  has_many :garage_items
  has_many :follows, as: :followable

  validates :name, presence: true, uniqueness: true
end

app/models/garage_item.rb
class GarageItem < ApplicationRecord
  belongs_to :garage
  belongs_to :generic_image
end

app/models/generic_image.rb
class GenericImage < ApplicationRecord
  mount_uploader :image, HomeImageUploader
  has_many :user_favorites
end

app/models/user.rb
class User < ApplicationRecord
  enum gender: [:male, :female]

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_favorites
  has_many :garages
  has_many :follows, as: :followable

  def users_im_following
    User.where(id: follows.where(followable_type: 'User').map(&:item_id))
  end

  def garages_im_following
    User.where(id: follows.where(followable_type: 'Garage').map(&:item_id))
  end
end

app/models/user_favorite.rb
class UserFavorite < ApplicationRecord
  belongs_to :user
  belongs_to :generic_image

  accepts_nested_attributes_for :generic_image
end

app/controllers/api/v1/base_api_controller.rb
module Api
  module V1
    class BaseApiController < ActionController::API
      def render_created
        render json: nil, status: :created
      end

      def render_unprocessable_entity
        render json: nil, status: :unprocessable_entity
      end

      def render_accepted
        render json: nil, status: :accepted
      end
    end
  end
end

app/controllers/api/v1/favorite_photos_controller.rb
module Api
  module V1
    class FavoritePhotosController < BaseApiController
      before_action :authenticate_user!

      def index
        render json: { status: 200 }
      end

      def update
        if !already_favorited? && current_user.user_favorites.create(
          generic_image: generic_image
        )
          render_created
        else
          render_unprocessable_entity
        end
      end

      def destroy
        if destroy_generic_image?
          render_accepted
        else
          render_unprocessable_entity
        end
      end

      private

      def already_favorited?
        current_user.user_favorites.map(&:generic_image_id).include?(
          generic_image.id
        )
      end

      def destroy_generic_image?
        generic_image_to_destroy = current_user.user_favorites.find_by(
          generic_image: generic_image
        )

        if generic_image_to_destroy
          generic_image_to_destroy.destroy
        else
          false
        end
      end

      def generic_image
        @generic_image = GenericImage.find(params[:id])
      end
    end
  end
end

app/controllers/api/v1/generic_images_controller.rb
module Api
  module V1
    class GenericImagesController < BaseApiController
      def index
        render json: GenericImage.all
      end
    end
  end
end

app/controllers/api/v1/users_controller.rb
module Api
  module V1
    class UsersController < ActionController::API
      def index
        render json: User.includes(:user_favorites).last(100)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @favorites = current_user.user_favorites.map(&:generic_image)
  end
end

app/controllers/garages_controller.rb
class GaragesController < ApplicationController
  def new
    @garage = current_user.garages.new
  end

  def create
    @garage = current_user.garages.new(garage_params)

    if @garage.save
      redirect_to profile_path
    else
      render :new
    end
  end

  private

  def garage_params
    params.require(:garage).permit(:name)
  end
end

app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
    @hello_world_props = { name: 'Stranger' }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @images = GenericImage.all
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  before_action :authenticate_user!

  def edit
    @user = current_user
  end

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def favorited?(generic_image)
    return unless current_user
    current_user.user_favorites.map(&:generic_image).include?(generic_image)
  end

  def number_of_likes(generic_image)
    generic_image.user_favorites.count
  end
end

app/views/favorites/index.html.erb
<%= render partial: 'generic_images/generic_image', collection: @favorites %>

app/views/garages/edit.html.erb
<h1>Garages#edit</h1>
<p>Find me in app/views/garages/edit.html.erb</p>

app/views/garages/index.html.erb
<h1>Garages#index</h1>
<p>Find me in app/views/garages/index.html.erb</p>

app/views/garages/new.html.erb
<%= simple_form_for @garage do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/garages/show.html.erb
<h1>Garages#show</h1>
<p>Find me in app/views/garages/show.html.erb</p>

app/views/generic_images/_generic_image.html.erb
<div class="brick">
  <div class="col-md-4">
    <div class="thumbnail" id=image-<%= generic_image.id %>>
      <%= image_tag generic_image.image.medium %>
      <div class="caption">
        <% if favorited? generic_image %>
          <span class="heart glyphicon glyphicon-heart" aria-hidden="true"></span>
        <% else %>
          <span class="heart-empty glyphicon glyphicon-heart-empty" aria-hidden="true"></span>
        <% end %>
        <span><i>Likes:</span> <span class="likes"><%= number_of_likes generic_image %></span>
          <button type="button" class="btn btn-standard" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Add to garage</button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Add to garage</h4>
      </div>
      <div class="modal-body">
          <div class="form-group">
            <label for="recipient-name" class="control-label">Garage:</label>
            <input type="text" class="form-control" id="recipient-name" placeholder="TODO">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Notes:</label>
            <textarea class="form-control" id="message-text"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Add</button>
      </div>
    </div>
  </div>
</div>

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorldApp", props: @hello_world_props, prerender: false) %>

app/views/home/show.html.erb
<div class="col-md-12" id="freewall">
  <div class="row">
    <%= render partial: 'generic_images/generic_image', collection: @images %>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Jeep Garage', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
          <ul class="dropdown-menu">
              <li><%= link_to "My profile", profile_path %></li>
            <li><%= link_to 'My favorites', favorites_path %></li>
            <% if !user_signed_in? %>
              <li><%= link_to 'Sign in', user_session_path %></li>
            <% else %>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jeep Garage</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= render 'layouts/nav' %>
    <%= yield %>
  </div>
  </body>
</html>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <li>
      <%= link_to user.full_name_and_age, user_path(user) %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<%= @user.full_name %>
<%= @user.age %>